#ifndef CONFIG_H
#define CONFIG_H

#define DAESOP_VERSION_MAJOR @THIRDEYE_VERSION_MAJOR@
#define DAESOP_VERSION_MINOR @THIRDEYE_VERSION_MINOR@
#define DAESOP_VERSION_RELEASE @THIRDEYE_VERSION_RELEASE@
#define DAESOP_VERSION "@THIRDEYE_VERSION@"

#endif
