#ifndef CONFIG_H
#define CONFIG_H

#define OPENADD_VERSION_MAJOR @OPENADD_VERSION_MAJOR@
#define OPENADD_VERSION_MINOR @OPENADD_VERSION_MINOR@
#define OPENADD_VERSION_RELEASE @OPENADD_VERSION_RELEASE@
#define OPENADD_VERSION "@OPENADD_VERSION@"

#endif
