#ifndef CONFIG_H
#define CONFIG_H

#define LAUNCHER_VERSION_MAJOR @THIRDEYE_VERSION_MAJOR@
#define LAUNCHER_VERSION_MINOR @THIRDEYE_VERSION_MINOR@
#define LAUNCHER_VERSION_RELEASE @THIRDEYE_VERSION_RELEASE@
#define LAUNCHER_VERSION "@THIRDEYE_VERSION@"

#endif
