#ifndef CONFIG_H
#define CONFIG_H

#define THIRDEYE_VERSION_MAJOR @THIRDEYE_VERSION_MAJOR@
#define THIRDEYE_VERSION_MINOR @THIRDEYE_VERSION_MINOR@
#define THIRDEYE_VERSION_RELEASE @THIRDEYE_VERSION_RELEASE@
#define THIRDEYE_VERSION "@THIRDEYE_VERSION@"

// Absolute path to the repo's files/ dir (holds SAMPLE.RES, bytecode.def, ...).
#define TESTS_DATA_DIR "@TESTS_DATA_DIR@"

#endif
